version: "3.9"

services:
  #Publisher
  publisher:
    image: cpabe-arm-dev-image:0.0
    build: ./dockerfiles/base-arm/
    tty: true
    volumes:
      - ./codes/Publisher/:/code
    working_dir: /code
    command: "/bin/bash"
    # environment:
  #Subscriber
  subscriber:
    image: cpabe-arm-dev-image:0.0
    build: ./dockerfiles/base-arm/
    tty: true
    volumes:
      - ./codes/Subscriber/:/code
    working_dir: /code
    command: "/bin/bash"
    # environment:
